/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/composeProvinder`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/provinder`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login/page` | `/login/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login/_container/login` | `/login/_container/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(private)'}${'/(tabs)'}/home/page` | `/home/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(private)'}${'/(tabs)'}/home/_container/home` | `/home/_container/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/home/page` | `/home/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/home/_container/home` | `/home/_container/home`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/composeProvinder`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/provinder`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login/page` | `/login/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login/_container/login` | `/login/_container/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(private)'}${'/(tabs)'}/home/page` | `/home/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(private)'}${'/(tabs)'}/home/_container/home` | `/home/_container/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/home/page` | `/home/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/home/_container/home` | `/home/_container/home`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/composeProvinder${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/provinder${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login/page${`?${string}` | `#${string}` | ''}` | `/login/page${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login/_container/login${`?${string}` | `#${string}` | ''}` | `/login/_container/login${`?${string}` | `#${string}` | ''}` | `${'/(private)'}${'/(tabs)'}/home/page${`?${string}` | `#${string}` | ''}` | `/home/page${`?${string}` | `#${string}` | ''}` | `${'/(private)'}${'/(tabs)'}/home/_container/home${`?${string}` | `#${string}` | ''}` | `/home/_container/home${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/home/page${`?${string}` | `#${string}` | ''}` | `/home/page${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/home/_container/home${`?${string}` | `#${string}` | ''}` | `/home/_container/home${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/composeProvinder`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/provinder`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login/page` | `/login/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login/_container/login` | `/login/_container/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(private)'}${'/(tabs)'}/home/page` | `/home/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(private)'}${'/(tabs)'}/home/_container/home` | `/home/_container/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/home/page` | `/home/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/home/_container/home` | `/home/_container/home`; params?: Router.UnknownInputParams; };
    }
  }
}
